import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="flex h-screen overflow-hidden">
      <Head>
        <title>Crypto-Watch | A Redis Stack Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="px-4 sm:px-6 lg:px-8 py-4 w-full max-w-9xl mx-auto">
          <div className="grid grid-cols-12 gap-6">Hello World!</div>
        </div>
      </main>
    </div>
  );
};

export default Home;
